#!/bin/sh

# dotenvx ext precommit
if command -v dotenvx 2>&1 >/dev/null
then
  dotenvx ext precommit
elif npx dotenvx -V >/dev/null 2>&1
then
  npx dotenvx ext precommit
else
  echo "[dotenvx][precommit] 'dotenvx' command not found"
  echo "[dotenvx][precommit] ? install it with [curl -fsS https://dotenvx.sh | sh]"
  echo "[dotenvx][precommit] ? other install options [https://dotenvx.com/docs/install]"
  exit 1
fi
