# We use the reserved private subnet 10.5.0.0/16 (::ffff:a05:0/112)
# https://en.wikipedia.org/wiki/Reserved_IP_addresses
name: website
services:
  tor:
    extends:
      file: ./src/tor/docker-compose.yml
      service: tor
    profiles:
      - production
    depends_on:
      nginx:
        condition: service_started
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      nginx:
  nginx:
    extends:
      file: ./src/docker-compose.yml
      service: nginx
    depends_on:
      'express':
        condition: 'service_started'
        required: false
    volumes:
      # Overwriting default config without affecting other default files
      - type: bind
        source: ./src/nginx/conf/nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
      # Adding custom configs
      - type: bind
        source: ./src/nginx/conf/conf.d/
        target: /etc/nginx/conf.d/
      # Adding custom HTML
      - type: bind
        source: ./src/nginx/html/
        target: /usr/local/openresty/nginx/html/
        read_only: true
    networks:
      nginx:
        ipv4_address: 10.5.0.2
      express:
        ipv4_address: 10.5.2.3
  nginx-debug:
    extends:
      file: ./src/docker-compose.yml
      service: container-link
    container_name: nginx-debug
    profiles:
      - development
    depends_on:
      - nginx
    environment:
      - FORWARD_ADDR=10.5.0.2:80
    ports:
      - :80
    networks:
      nginx:
        ipv4_address: 10.5.0.254
  express:
    extends:
      file: ./src/docker-compose.yml
      service: express
    depends_on:
      mongo:
        # mongo will restart on its first run, causing this check to fail
        condition: service_healthy
        required: false
    secrets:
      - source: express
        target: /project/secrets/
    networks:
      express:
        ipv4_address: 10.5.2.2
      mongo:
  express-debug:
    extends:
      file: ./src/docker-compose.yml
      service: container-link
    container_name: express-debug
    profiles:
      - development
    depends_on:
      - express
    environment:
      - FORWARD_ADDR=10.5.2.2:3000
      - EXPOSE_PORT=3000
    ports:
      - :3000
    networks:
      express:
        ipv4_address: 10.5.2.254
  mongo:
    extends:
      file: ./src/docker-compose.yml
      service: mongo
    volumes:
      - type: 'volume'
        source: 'mongo-db'
        target: '/data/db'
      - type: 'volume'
        source: 'mongo-configdb'
        target: '/data/configdb'
    env_file: './src/mongo/secrets/.env'
    networks:
      - 'mongo'
  mongo-debug:
    extends:
      file: ./src/docker-compose.yml
      service: mongo-debug
    profiles:
      - development
    depends_on:
      mongo:
        # mongo will restart on its first run, causing this check to fail
        condition: service_healthy
        required: false
    ports:
      - :8081
    environment:
      # Standard configuration details
      - ME_CONFIG_BASICAUTH_ENABLED=true
      - ME_CONFIG_MONGODB_AUTHDB=admin
      - ME_CONFIG_MONGODB_CONTAINERNAME=mongo
      - ME_CONFIG_MONGODB_SERVER=mongo
      # Administrator credentials
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/root/username.txt
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/root/password.txt
      # Dev credentials used to log into the web UI
      - ME_CONFIG_BASICAUTH_USERNAME_FILE=/run/secrets/dev/username.txt
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/dev/password.txt
      # Theme demo:
      # https://codemirror.com/5/demo/theme.html#tomorrow-night-bright
      - ME_CONFIG_OPTIONS_EDITORTHEME=tomorrow-night-bright
    networks:
      mongo:
        ipv4_address: 10.5.1.254
  onionscan:
    extends:
      file: ./src/docker-compose.yml
      service: onionscan
    profiles:
      - production
      - onionscan
    depends_on:
      - tor
    env_file:
      - ./src/onionscan/.env
    environment:
      - TOR_PROXY=10.5.3.2:9050
    volumes:
      - type: volume
        source: onionscan-db
        target: /project/onionscandb/
    networks:
      tor:
        ipv4_address: 10.5.3.254
  license-report:
    extends:
      file: ./src/docker-compose.yml
      service: license-report
    profiles:
      - license-report
    volumes:
      - type: 'bind'
        source: './node_modules/'
        target: '/project/packages/node_modules/'
        read_only: true
volumes:
  mongo-db:
  mongo-configdb:
  onionscan-db:
secrets:
  tor-hostname:
    file: ./src/tor/secrets/hostname
  express:
    file: ./src/express/secrets/
  mongo-config:
    file: ./src/mongo/secrets/.env
  mongo-root-username:
    file: ./src/mongo/secrets/root/username.txt
  mongo-root-password:
    file: ./src/mongo/secrets/root/password.txt
  mongo-username:
    file: ./src/mongo/secrets/express/username.txt
  mongo-password:
    file: ./src/mongo/secrets/express/password.txt
  mongo-dev-username:
    file: ./src/mongo/secrets/dev/username.txt
  mongo-dev-password:
    file: ./src/mongo/secrets/dev/password.txt
networks:
  tor:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.5.3.0/24
          gateway: 10.5.3.1
  nginx:
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
  express:
    ipam:
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.1
  mongo:
    ipam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.1
