# We use the reserved private subnet 10.5.0.0/16 (::ffff:a05:0/112)
# https://en.wikipedia.org/wiki/Reserved_IP_addresses
name: website
services:
  tor:
    extends:
      file: ./src/tor/docker-compose.yml
      service: tor
    profiles:
      - production
    depends_on:
      nginx:
        condition: service_healthy
    healthcheck:
      # Makes sure the hidden service is reachable
      test: [
        'CMD-SHELL',
        'curl -s --socks4a 10.5.3.2:9050 "$(cat /var/lib/tor/website/hostname)" >/dev/null'
      ]
      interval: 10s
      timeout: 120s
      start_period: 20s
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      nginx:
  nginx:
    extends:
      file: ./src/docker-compose.yml
      service: nginx
    depends_on:
      express:
        condition: service_healthy
        required: false
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost']
      timeout: 5s
    volumes:
      # Overwriting default config without affecting other default files
      - type: bind
        source: ./src/nginx/conf/nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
      # Adding custom configs
      - type: bind
        source: ./src/nginx/conf/conf.d/
        target: /etc/nginx/conf.d/
      # Adding custom HTML
      - type: bind
        source: ./src/nginx/html/
        target: /usr/local/openresty/nginx/html/
        read_only: true
    environment:
      - PROXY_ADDRESS=http://10.5.2.2:3000
    secrets:
      - source: tor-hostname
        target: /run/secrets/hostname
    networks:
      nginx:
        ipv4_address: 10.5.0.2
      express:
        ipv4_address: 10.5.2.3
  nginx-debug:
    extends:
      file: ./src/docker-compose.yml
      service: container-link
    container_name: nginx-debug
    profiles:
      - development
    depends_on:
      - nginx
    environment:
      - FORWARD_ADDR=10.5.0.2:80
    ports:
      - :80
    networks:
      nginx:
        ipv4_address: 10.5.0.254
  express:
    extends:
      file: ./src/docker-compose.yml
      service: express
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    secrets:
      - source: express
        target: /project/secrets/
    networks:
      express:
        ipv4_address: 10.5.2.2
      mongo:
  express-debug:
    extends:
      file: ./src/docker-compose.yml
      service: container-link
    container_name: express-debug
    profiles:
      - development
    depends_on:
      - express
    environment:
      - FORWARD_ADDR=10.5.2.2:3000
      - EXPOSE_PORT=3000
    ports:
      - :3000
    networks:
      express:
        ipv4_address: 10.5.2.254
  mongo-init:
    extends:
      file: ./src/docker-compose.yml
      service: mongo-init
    depends_on:
      # Replicas will die until this service initializes the replica set
      - mongo-1
      - mongo-2
      - mongo-3
    environment:
      - HOST=mongo-1
    networks:
      - mongo
  mongo-1:
    extends:
      file: ./src/docker-compose.yml
      service: mongo
    container_name: mongo-1
    volumes:
      - type: volume
        source: mongo-db-1
        target: /data/db
        # Only necessary if sharding is used
      - type: volume
        source: mongo-configdb-1
        target: /data/configdb
    env_file: ./src/mongo/secrets/.env
    networks:
      - mongo
  mongo-2:
    extends:
      file: ./src/docker-compose.yml
      service: mongo
    container_name: mongo-2
    volumes:
      - type: volume
        source: mongo-db-2
        target: /data/db
        # Only necessary if sharding is used
      - type: volume
        source: mongo-configdb-2
        target: /data/configdb
    env_file: ./src/mongo/secrets/.env
    networks:
      - mongo
  mongo-3:
    extends:
      file: ./src/docker-compose.yml
      service: mongo
    container_name: mongo-3
    volumes:
      - type: volume
        source: mongo-db-3
        target: /data/db
        # Only necessary if sharding is used
      - type: volume
        source: mongo-configdb-3
        target: /data/configdb
    env_file: ./src/mongo/secrets/.env
    networks:
      - mongo
  mongo-debug:
    extends:
      file: ./src/docker-compose.yml
      service: mongo-debug
    profiles:
      - development
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    ports:
      - :8081
    environment:
      # Standard configuration details
      - ME_CONFIG_BASICAUTH_ENABLED=true
      - ME_CONFIG_MONGODB_AUTHDB=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017?replicaSet=dataset
      # Administrator credentials
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/root/username.txt
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/root/password.txt
      # Dev credentials used to log into the web UI
      - ME_CONFIG_BASICAUTH_USERNAME_FILE=/run/secrets/dev/username.txt
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/dev/password.txt
      # Theme demo:
      # https://codemirror.com/5/demo/theme.html#tomorrow-night-bright
      - ME_CONFIG_OPTIONS_EDITORTHEME=tomorrow-night-bright
    networks:
      mongo:
        ipv4_address: 10.5.1.254
  onionprobe:
    extends:
      file: ./src/docker-compose.yml
      service: onionprobe
    profiles:
      - production
    environment:
      - ONIONPROBE_CONFIG=/project/config.yml
    volumes:
      - type: bind
        source: ./src/onionprobe/config.yml
        target: /project/config.yml
        read_only: true
    depends_on:
      tor:
        condition: service_healthy
        required: false
    networks:
      tor:
        ipv4_address: 10.5.3.252
      metrics:
  prometheus:
    extends:
      file: ./src/docker-compose.yml
      service: prometheus
    profiles:
      - production
    depends_on:
      onionprobe:
        condition: service_started
        required: false
    volumes:
      - type: volume
        source: prometheus
        target: /prometheus/
      - type: bind
        source: ./src/onionprobe/onionprobe/configs/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: ./src/onionprobe/onionprobe/configs/prometheus/prometheus-rules.yml
        target: /etc/prometheus/prometheus-rules.yml
        read_only: true
      - type: bind
        source: ./src/onionprobe/onionprobe/configs/prometheus/prometheus-tests.yml
        target: /etc/prometheus/prometheus-tests.yml
        read_only: true
    networks:
      - metrics
  grafana:
    extends:
      file: ./src/docker-compose.yml
      service: grafana
    profiles:
      - production
    depends_on:
      prometheus:
        condition: service_started
        required: false
    ports:
      - ':3000'
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/home.json
      - GF_SECURITY_ADMIN_USER=$$__file{/run/secrets/username.txt}
      - GF_SECURITY_ADMIN_PASSWORD=$$__file{/run/secrets/password.txt}
      - GF_SECURITY_ADMIN_EMAIL=$$__file{/run/secrets/email.txt}
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana/
      - type: bind
        source: ./src/grafana/datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yml
        read_only: true
      - type: bind
        source: ./src/onionprobe/onionprobe/configs/grafana/home.json
        target: /etc/grafana/home.json
        read_only: true
    secrets:
      - source: grafana-admin-username
        target: /run/secrets/username.txt
      - source: grafana-admin-password
        target: /run/secrets/password.txt
      - source: grafana-admin-email
        target: /run/secrets/email.txt
    networks:
      - metrics
  onionscan:
    extends:
      file: ./src/docker-compose.yml
      service: onionscan
    profiles:
      - production
      - onionscan
    depends_on:
      tor:
        condition: service_healthy
    command: [
      "--verbose",
      "--torProxyAddress", "10.5.3.2:9050",
      "--list", "/run/secrets/hostname"
    ]
    volumes:
      - type: volume
        source: onionscan-db
        target: /project/onionscandb/
    networks:
      tor:
        ipv4_address: 10.5.3.254
  onionscan-ui:
    extends:
      file: ./src/docker-compose.yml
      service: onionscan-ui
    profiles:
      - production
      - onionscan
    depends_on:
      onionscan:
        # If the crawl DB already exists, we can search it.
        # If not, Onionscan should make one
        condition: service_started
        required: false
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8080" ]
    ports:
      - :8080
    volumes:
      - type: volume
        source: onionscan-db
        target: /project/onionscandb/
    networks:
      tor:
        ipv4_address: 10.5.3.253
  license-report:
    extends:
      file: ./src/docker-compose.yml
      service: license-report
    profiles:
      - license-report
    volumes:
      - type: 'bind'
        source: './node_modules/'
        target: '/project/packages/node_modules/'
        read_only: true
configs:
  mongo-replicas:
    file: ./src/mongo/replicas.json
volumes:
  mongo-configdb-1:
  mongo-configdb-2:
  mongo-configdb-3:
  mongo-db-1:
  mongo-db-2:
  mongo-db-3:
  prometheus:
  grafana-storage:
  onionscan-db:
secrets:
  tor-hostname:
    file: ./src/tor/secrets/hostname
  express:
    file: ./src/express/secrets/
  mongo-config:
    file: ./src/mongo/secrets/.env
  mongo-keyfile:
    file: ./src/mongo/secrets/keyFile.pem
  mongo-root-username:
    file: ./src/mongo/secrets/root/username.txt
  mongo-root-password:
    file: ./src/mongo/secrets/root/password.txt
  mongo-username:
    file: ./src/mongo/secrets/express/username.txt
  mongo-password:
    file: ./src/mongo/secrets/express/password.txt
  mongo-dev-username:
    file: ./src/mongo/secrets/dev/username.txt
  mongo-dev-password:
    file: ./src/mongo/secrets/dev/password.txt
  grafana-admin-username:
    file: ./src/grafana/secrets/username.txt
  grafana-admin-password:
    file: ./src/grafana/secrets/password.txt
  grafana-admin-email:
    file: ./src/grafana/secrets/email.txt
networks:
  tor:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.5.3.0/24
          gateway: 10.5.3.1
  nginx:
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
  express:
    ipam:
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.1
  mongo:
    ipam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.1
  metrics:
    ipam:
      config:
        - subnet: 10.5.4.0/24
          gateway: 10.5.4.1
