# We use the reserved private subnet 10.5.0.0/16 (::ffff:a05:0/112)
# https://en.wikipedia.org/wiki/Reserved_IP_addresses
name: 'website'
services:
  'tor-init':
    container_name: 'tor-init'
    profiles:
      - 'production'
    restart: 'no'
    build:
      context: './src/tor'
      dockerfile: './Dockerfile'
      target: 'init'
    volumes:
      - type: 'bind'
        source: './src/tor/secrets/'
        target: '/secrets/'
    network_mode: 'none'
  'tor':
    container_name: 'tor'
    profiles:
      - 'production'
    depends_on:
      'tor-init':
        condition: 'service_completed_successfully'
        required: true
      'nginx':
        condition: 'service_started'
        required: true
    build:
      context: './src/tor'
      dockerfile: './Dockerfile'
      target: 'run'
    volumes:
      - type: 'bind'
        source: './src/tor/secrets/'
        target: '/var/lib/tor/website/'
      - type: 'volume'
        source: 'tor-data'
        target: '/var/lib/tor/'
    sysctls:
      - 'net.ipv6.conf.all.disable_ipv6=0'
    networks:
      'tor':
        ipv4_address: '10.5.3.2'
      'nginx':
  'vanguards':
    container_name: 'vanguards'
    profiles:
      - 'production'
    depends_on:
      - 'tor'
    build:
      context: './src/vanguards'
      dockerfile: './Dockerfile'
    volumes:
      - type: 'volume'
        source: 'tor-data'
        target: '/var/lib/tor/'
        read_only: true
    network_mode: 'container:tor'
  'nginx':
    container_name: 'nginx'
    depends_on:
      'express':
        condition: 'service_started'
        required: false
    build:
      context: './src/nginx'
      dockerfile: './Dockerfile'
      target: 'openresty-gixy'
    volumes:
      # Overwriting default config without affecting other default files
      - type: 'bind'
        source: './src/nginx/conf/nginx.conf'
        target: '/usr/local/openresty/nginx/conf/nginx.conf'
      # Adding custom configs
      - type: 'bind'
        source: './src/nginx/conf/conf.d/'
        target: '/etc/nginx/conf.d/'
      # Adding custom HTML
      - type: 'bind'
        source: './src/nginx/html/'
        target: '/usr/local/openresty/nginx/html/'
        read_only: true
    secrets:
      - source: 'tor-hostname'
        target: '/run/secrets/hostname'
    networks:
      'nginx':
        ipv4_address: '10.5.0.2'
      'express':
        ipv4_address: '10.5.2.3'
  'nginx-debug':
    container_name: 'nginx-debug'
    profiles:
      - 'development'
    depends_on:
      - nginx
    build:
      context: './src/container-link'
      dockerfile: './Dockerfile'
    environment:
      - 'FORWARD_ADDR=10.5.0.2:80'
    ports:
      - ':80'
    networks:
      'nginx':
        ipv4_address: '10.5.0.254'
  'express':
    container_name: 'express'
    restart: 'on-failure'
    depends_on:
      'mongo':
        # mongo will restart on its first run, causing this check to fail
        condition: 'service_healthy'
        required: false
    build:
      context: './src/express'
      dockerfile: './Dockerfile'
    secrets:
      - source: 'express'
        target: '/project/src/secrets/'
    networks:
      'express':
        ipv4_address: '10.5.2.2'
      'mongo':
  'express-debug':
    container_name: 'express-debug'
    profiles:
      - 'development'
    depends_on:
      - express
    build:
      context: './src/container-link'
      dockerfile: './Dockerfile'
    environment:
      - 'FORWARD_ADDR=10.5.2.2:3000'
      - 'EXPOSE_PORT=3000'
    ports:
      - ':3000'
    networks:
      'express':
        ipv4_address: '10.5.2.254'
  'mongo':
    container_name: 'mongo'
    restart: 'on-failure'
    mem_swappiness: 1 # Doesn't affect /proc/sys/vm/swappiness, so mongosh still gives a warning
    build:
      context: './src/mongo'
      dockerfile: './Dockerfile'
      target: 'run'
    volumes:
      - type: 'volume'
        source: 'mongo-db'
        target: '/data/db'
      - type: 'volume'
        source: 'mongo-configdb'
        target: '/data/configdb'
    env_file: './src/mongo/secrets/.env'
    secrets:
      - source: 'mongo-config'
        target: '/run/secrets/.env'
      - source: 'mongo-root-username'
        target: '/run/secrets/root/username.txt'
      - source: 'mongo-root-password'
        target: '/run/secrets/root/password.txt'
      - source: 'mongo-username'
        target: '/run/secrets/express/username.txt'
      - source: 'mongo-password'
        target: '/run/secrets/express/password.txt'
    networks:
      - 'mongo'
  'mongo-debug':
    container_name: 'mongo-debug'
    profiles:
      - 'development'
    depends_on:
      'mongo':
        # mongo will restart on its first run, causing this check to fail
        condition: 'service_healthy'
        required: false
    restart: 'on-failure'
    image: 'mongo-express:latest@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64'
    ports:
      - ':8081'
    environment:
      # Standard configuration details
      'ME_CONFIG_BASICAUTH_ENABLED': 'true'
      'ME_CONFIG_MONGODB_AUTHDB': 'admin'
      'ME_CONFIG_MONGODB_CONTAINERNAME': 'mongo'
      'ME_CONFIG_MONGODB_SERVER': 'mongo'
      # Administrator credentials
      'ME_CONFIG_MONGODB_ADMINUSERNAME_FILE': '/run/secrets/root/username.txt'
      'ME_CONFIG_MONGODB_ADMINPASSWORD_FILE': '/run/secrets/root/password.txt'
      # Dev credentials used to log into the web UI
      'ME_CONFIG_BASICAUTH_USERNAME_FILE': '/run/secrets/dev/username.txt'
      'ME_CONFIG_BASICAUTH_PASSWORD_FILE': '/run/secrets/dev/password.txt'
      # Theme demo:
      # https://codemirror.com/5/demo/theme.html#tomorrow-night-bright
      'ME_CONFIG_OPTIONS_EDITORTHEME': 'tomorrow-night-bright'
    secrets:
      - source: 'mongo-root-username'
        target: '/run/secrets/root/username.txt'
      - source: 'mongo-root-password'
        target: '/run/secrets/root/password.txt'
      - source: 'mongo-dev-username'
        target: '/run/secrets/dev/username.txt'
      - source: 'mongo-dev-password'
        target: '/run/secrets/dev/password.txt'
    networks:
      'mongo':
        ipv4_address: '10.5.1.254'
  'onionscan':
    container_name: 'onionscan'
    restart: 'always'
    profiles:
      - 'production'
      - 'onionscan'
    build:
      context: './src/onionscan'
      dockerfile: './Dockerfile'
      target: 'onionscan'
    env_file:
      - './src/onionscan/.env'
    environment:
      - 'TOR_PROXY=10.5.3.2:9050'
    volumes:
      - type: 'volume'
        source: 'onionscan-db'
        target: '/project/onionscandb/'
    networks:
      'tor':
        ipv4_address: '10.5.3.254'
  'license-report':
    container_name: 'license-report'
    profiles:
      - 'license-report'
    build:
      context: '.'
      dockerfile: './src/license-report/Dockerfile'
    # If we have node modules installed, inspect them.
    # If we don't, only inspect package.json
    working_dir: '/project/packages/'
    volumes:
      - type: 'bind'
        source: './node_modules/'
        target: '/project/packages/node_modules/'
        read_only: true
volumes:
  'tor-data':
  'mongo-db':
  'mongo-configdb':
  'onionscan-db':
secrets:
  'tor-hostname':
    file: './src/tor/secrets/hostname'
  'express':
    file: './src/express/secrets/'
  'mongo-config':
    file: './src/mongo/secrets/.env'
  'mongo-root-username':
    file: './src/mongo/secrets/root/username.txt'
  'mongo-root-password':
    file: './src/mongo/secrets/root/password.txt'
  'mongo-username':
    file: './src/mongo/secrets/express/username.txt'
  'mongo-password':
    file: './src/mongo/secrets/express/password.txt'
  'mongo-dev-username':
    file: './src/mongo/secrets/dev/username.txt'
  'mongo-dev-password':
    file: './src/mongo/secrets/dev/password.txt'
networks:
  'tor':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: true
    ipam:
      config:
        - subnet: '10.5.3.0/24'
          gateway: '10.5.3.1'
  'nginx':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: '10.5.0.0/24'
          gateway: '10.5.0.1'
  'express':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: '10.5.2.0/24'
          gateway: '10.5.2.1'
  'mongo':
    driver: 'bridge'
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: '10.5.1.0/24'
          gateway: '10.5.1.1'
