name: website
services:
  tor:
    extends:
      file: ../docker-compose.yml
      service: tor
    volumes:
      - type: bind
        source: ./torrc
        target: /etc/tor/torrc
      # Path defined by torrc
      - type: bind
        source: ./secrets/
        target: /var/lib/tor/website/
    networks:
      tor:
        ipv4_address: 10.5.3.2
networks:
  tor:
    ipam:
      config:
        - subnet: 10.5.3.0/24
          gateway: 10.5.3.1
