server {
    server_name localhost;

    # HTTP
    listen 80;

    # HTTPS
    #listen 443;

    #charset koi8-r;
    access_log logs/host.access.log main;

    set $onion_domain ''; # Gixy doesn't parse lua code
    set_by_lua_block $onion_domain {
        local file, msg = io.open('/run/secrets/hostname', 'r')

        -- Validating file can be read
        if file == nil then
            print(string.format("Couldn't read hostname file: %s", msg))
            return ''
        end

        local hostname = string.lower(file:read())
        io.close(file)

        -- Validating Onion v3 address
        local pattern = '^' .. string.rep("%w", 56) .. '%.onion'

        if string.match(hostname, pattern) == nil then
            print(string.format('Ignoring invalid hostname: %s', hostname))
            return ''
        end

        return string.format('http://%s%s', hostname, ngx.var.request_uri)
    }

    location / {
        # Only allowing these HTTP methods
        limit_except GET POST HEAD {
            deny all;
        }

        # If variable is present and response is 2XX, adding header
        more_set_headers -s '200 201 202 203 204 205 206 207 208 226' "Onion-Location: $onion_domain";

        # Proxying requests to Express
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass 'http://10.5.2.2:3000';
    }

    # Redirecting 4XX/5XX server errors to the static error page
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 @error;
    location @error {
        internal;
        root /usr/local/openresty/nginx/html;
        try_files /error.html =500; # Returns 500 Internal Server Error if error page is missing
        open_file_cache max=1000 inactive=20s;
        sub_filter '<!--@NGINX_ERROR_CODE-->' $status;
        sub_filter '<!--@NGINX_ERROR_MESSAGE-->' $status_text;
        sub_filter_once off; # Perform multiple substitutions
    }
}
