name: CI

on:
  push:

env:
  DOCKER_COMPOSE_VERSION: v5.1.1

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Compose stack
        run: npm run build
  eslint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm i
      - name: Run eslint
        run: npm run eslint
  tsc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm i
      - name: Run tsc
        run: npm run tsc
