name: CI

on:
  push:

env:
  DOCKER_COMPOSE_VERSION: v5.1.2

jobs:
  # Builds Docker compose services
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Compose stack
        run: npm run build
  # Runs a linting check
  eslint:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm i
      - name: Run eslint
        run: npm run eslint
  # Runs a TypeScript type check
  tsc:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm i
      - name: Run tsc
        run: npm run tsc
